name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: self-hosted
    container:
      image: node:18
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Check for dockerenv file
        run: npm install

      - name: Build and Test
        run: |
          npm run build
          ls -l
          pwd
      - name: Create ZIP file
        run: |
           apt-get install zip -y
           zip -r  $workspace/dist.zip . 
           
      # - name: Copy artifacts to S3
      #   run:  |
      #       aws s3 cp  $workspace/api-flyakeed.zip  s3://$ARTIFACTS/${{ github.repository }}/api-flyakeed.zip
      #       rm  $workspace/api-flyakeed.zip 
        
